- resources:
    cpu: true
    memory: true
    disk: /
    expanded: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short

- docker:
    host: my-docker
    label: Containers

- openmeteo:
    label: "Santo Domingo Este"
    latitude: 18.4884
    longitude: -69.8571
    units: metric
    cache: 30
