- resources:
    cpu: true
    memory: true
    disk: /
    expanded: true

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
