---
- name: Run Homelab Server-Side Backups
  hosts: automation
  tasks:
    - name: Run Unified Daily Backup Script
      ansible.builtin.script:
        cmd: ../../scripts/backup_server.sh
      register: backup_output

    - name: Show Backup Output Logs
      ansible.builtin.debug:
        var: backup_output.stdout_lines
