---
- name: Run Terraform Provisioning
  hosts: localhost
  connection: local
  tasks:
    - name: Run Terraform Init & Apply
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../hypervisor/proxmox/terraform"
        state: present
        force_init: true
      register: tf_result

    - name: Display Terraform Output
      ansible.builtin.debug:
        var: tf_result.stdout_lines
