---
- name: Run Terraform Provisioning
  hosts: localhost
  connection: local
  tasks:
    - name: Run Terraform Init & Apply
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../hypervisor/proxmox/terraform"
        state: present
        force_init: true
        variables:
          proxmox_endpoint: "{{ proxmox_endpoint }}"
          proxmox_api_token: "{{ proxmox_api_token }}"
      register: tf_result

    - name: Display Terraform Output
      ansible.builtin.debug:
        var: tf_result.stdout_lines
