services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=10.0.0.67:3000,localhost:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    dns:
      - 10.0.0.20
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
