[automation]
automation-01 ansible_host=10.0.0.67 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[docker_servers]
docker-01 ansible_host=10.0.0.33 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[database_servers]
colmado-db ansible_host=10.0.0.35 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[security]
security-01 ansible_host=10.0.0.40 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[proxmox_hosts]
proxmox-main ansible_host=10.0.0.167 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[linux_servers:children]
automation
docker_servers
database_servers
security
