[automation]
automation-01 ansible_host=automation-01 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[docker_servers]
docker-01 ansible_host=docker ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[database_servers]
colmado-db ansible_host=yzee ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[security]
security-01 ansible_host=security-01 ansible_user=yzee ansible_python_interpreter=/usr/bin/python3

[proxmox_hosts]
proxmox-main ansible_host=proxmox ansible_user=root ansible_python_interpreter=/usr/bin/python3

[linux_servers:children]
automation
docker_servers
database_servers
security
